/*! This file is generated by build.rs !*/

use crate::common::MakefileTarget;
use std::collections::HashMap;
use lazy_static::lazy_static;

lazy_static! {
pub(crate) static ref TASK_DEPENDENCIES: HashMap<MakefileTarget, Vec<MakefileTarget>> =
create_lookup();
}

fn create_lookup() -> HashMap<MakefileTarget, Vec<MakefileTarget>> {
let mut map = HashMap::new();
map.insert(
            MakefileTarget::UploadOvaBase,vec![
MakefileTarget::SetupBuild,
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::Ami,vec![
MakefileTarget::SetupBuild,
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::AmiPrivate,vec![
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::AmiPublic,vec![
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::BootConfig,vec![
MakefileTarget::FetchSdk,
]);
map.insert(
            MakefileTarget::Build,vec![
MakefileTarget::CheckLicenses,
MakefileTarget::FetchLicenses,
MakefileTarget::BuildVariant,
]);
map.insert(
            MakefileTarget::BuildPackage,vec![
MakefileTarget::CheckCargoVersion,
MakefileTarget::FetchSdk,
MakefileTarget::BuildTools,
MakefileTarget::PublishSetup,
MakefileTarget::FetchLicenses,
]);
map.insert(
            MakefileTarget::BuildSbkeys,vec![
MakefileTarget::Fetch,
]);
map.insert(
            MakefileTarget::BuildTools,vec![
MakefileTarget::Setup,
MakefileTarget::FetchSources,
]);
map.insert(
            MakefileTarget::BuildVariant,vec![
MakefileTarget::FetchSdk,
MakefileTarget::BuildTools,
MakefileTarget::BuildSbkeys,
MakefileTarget::PublishSetup,
]);
map.insert(
            MakefileTarget::Check,vec![
MakefileTarget::CheckCargoVersion,
MakefileTarget::UnitTests,
MakefileTarget::CheckFmt,
MakefileTarget::CheckLints,
MakefileTarget::CheckMigrations,
]);
map.insert(
            MakefileTarget::CheckCargoVersion,vec![
]);
map.insert(
            MakefileTarget::CheckClippy,vec![
]);
map.insert(
            MakefileTarget::CheckFmt,vec![
]);
map.insert(
            MakefileTarget::CheckGolangciLint,vec![
]);
map.insert(
            MakefileTarget::CheckLicenses,vec![
MakefileTarget::Fetch,
]);
map.insert(
            MakefileTarget::CheckLints,vec![
MakefileTarget::CheckClippy,
MakefileTarget::CheckShell,
MakefileTarget::CheckGolangciLint,
]);
map.insert(
            MakefileTarget::CheckMigrations,vec![
]);
map.insert(
            MakefileTarget::CheckRepoExpirations,vec![
MakefileTarget::PublishSetupWithoutKey,
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::CheckShell,vec![
]);
map.insert(
            MakefileTarget::Clean,vec![
MakefileTarget::CleanSources,
MakefileTarget::CleanPackages,
MakefileTarget::CleanImages,
MakefileTarget::CleanRepos,
MakefileTarget::CleanState,
]);
map.insert(
            MakefileTarget::CleanImages,vec![
]);
map.insert(
            MakefileTarget::CleanPackages,vec![
]);
map.insert(
            MakefileTarget::CleanRepos,vec![
]);
map.insert(
            MakefileTarget::CleanSources,vec![
]);
map.insert(
            MakefileTarget::CleanState,vec![
]);
map.insert(
            MakefileTarget::CleanTest,vec![
MakefileTarget::TestTools,
]);
map.insert(
            MakefileTarget::CreateInfra,vec![
MakefileTarget::InfraTools,
]);
map.insert(
            MakefileTarget::Default,vec![
]);
map.insert(
            MakefileTarget::Fetch,vec![
MakefileTarget::FetchSdk,
MakefileTarget::FetchToolchain,
MakefileTarget::FetchSources,
MakefileTarget::FetchVendored,
]);
map.insert(
            MakefileTarget::FetchLicenses,vec![
MakefileTarget::Fetch,
]);
map.insert(
            MakefileTarget::FetchSdk,vec![
MakefileTarget::SetupBuild,
]);
map.insert(
            MakefileTarget::FetchSources,vec![
MakefileTarget::Setup,
]);
map.insert(
            MakefileTarget::FetchToolchain,vec![
MakefileTarget::SetupBuild,
]);
map.insert(
            MakefileTarget::FetchVendored,vec![
MakefileTarget::FetchSdk,
]);
map.insert(
            MakefileTarget::GrantAmi,vec![
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::InfraTools,vec![
MakefileTarget::Setup,
MakefileTarget::FetchSources,
MakefileTarget::Tuftool,
]);
map.insert(
            MakefileTarget::LogTest,vec![
MakefileTarget::TestTools,
]);
map.insert(
            MakefileTarget::PromoteSsm,vec![
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::PublishSetup,vec![
MakefileTarget::PublishSetupTools,
]);
map.insert(
            MakefileTarget::PublishSetupTools,vec![
MakefileTarget::Setup,
MakefileTarget::FetchSources,
MakefileTarget::Tuftool,
]);
map.insert(
            MakefileTarget::PublishSetupWithoutKey,vec![
]);
map.insert(
            MakefileTarget::PublishTools,vec![
MakefileTarget::Setup,
MakefileTarget::FetchSources,
]);
map.insert(
            MakefileTarget::PurgeCache,vec![
MakefileTarget::PurgeGoVendor,
MakefileTarget::PurgeCargo,
]);
map.insert(
            MakefileTarget::PurgeCargo,vec![
]);
map.insert(
            MakefileTarget::PurgeGoVendor,vec![
]);
map.insert(
            MakefileTarget::PurgeTest,vec![
MakefileTarget::TestTools,
MakefileTarget::ResetTest,
MakefileTarget::UninstallTest,
]);
map.insert(
            MakefileTarget::RefreshRepo,vec![
MakefileTarget::PublishSetup,
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::Repo,vec![
MakefileTarget::PublishSetup,
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::ResetTest,vec![
MakefileTarget::TestTools,
]);
map.insert(
            MakefileTarget::RevokeAmi,vec![
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::Setup,vec![
]);
map.insert(
            MakefileTarget::SetupBuild,vec![
MakefileTarget::Setup,
]);
map.insert(
            MakefileTarget::SetupTest,vec![
MakefileTarget::TestTools,
]);
map.insert(
            MakefileTarget::Ssm,vec![
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::Test,vec![
MakefileTarget::TestTools,
]);
map.insert(
            MakefileTarget::TestTools,vec![
MakefileTarget::Setup,
MakefileTarget::FetchSources,
]);
map.insert(
            MakefileTarget::Testsys,vec![
MakefileTarget::TestTools,
]);
map.insert(
            MakefileTarget::Tuftool,vec![
]);
map.insert(
            MakefileTarget::UninstallTest,vec![
MakefileTarget::TestTools,
]);
map.insert(
            MakefileTarget::UnitTests,vec![
MakefileTarget::FetchSdk,
MakefileTarget::FetchSources,
MakefileTarget::FetchVendored,
]);
map.insert(
            MakefileTarget::UploadOva,vec![
]);
map.insert(
            MakefileTarget::ValidateAmi,vec![
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::ValidateBootConfig,vec![
MakefileTarget::FetchSdk,
]);
map.insert(
            MakefileTarget::ValidateRepo,vec![
MakefileTarget::PublishSetupWithoutKey,
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::ValidateSsm,vec![
MakefileTarget::PublishTools,
]);
map.insert(
            MakefileTarget::VmwareTemplate,vec![
]);
map.insert(
            MakefileTarget::WatchTest,vec![
MakefileTarget::TestTools,
]);
map.insert(
            MakefileTarget::WatchTestAll,vec![
MakefileTarget::TestTools,
]);
map
}



































