name: Rust
on:
  # triggers when a PR is posted
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - "**.plantuml"
      - "**.svg"
  # triggers when a PR is merged
  push:
    branches: [develop]
    paths-ignore:
      - "**.md"
      - "**.plantuml"
      - "**.svg"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTC_BOOTSTRAP: "1"
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --locked
      - run: cargo test --locked
      - run: cargo fmt -- --check
      - run: cargo clippy --locked -- -D warnings --no-deps
